---
nautobot:
  image:
    registry: "ghcr.io"
    repository: "byrn-baker/nautobot-kubernetes"
    tag: "v0.0.6"
    pullSecrets:
      - "ghcr.io"
  replicaCount: 2
  metrics: true
  superUser:
    enabled: true
    username: "admin"
    password: "admin"
  extraVars:
    - name: "NAUTOBOT_BANNER_TOP"
      value: "HomeLab"
workers:
  default:
    replicaCount: 2
postgresql:
  enabled: true
  auth:
    password: "SuperSecret123"
redis:
  enabled: true 
  auth:
    password: "SuperSecret456"