---
postgresql:
  postgresqlPassword: "SuperSecret123"
redis:
  auth:
    password: "SuperSecret456"
nautobot:
  image:
    registry: "ghcr.io"
    repository: "networktocode/nautobot-kubernetes"
    tag: "main"
    pullSecrets:
      - "ghcr.io"